// (c) Name
// WK5 - PE

#include <iostream>
using namespace std;

int main( ) {

    double x;

    cout << "Input an integer between 0 and 100 inclusive: ";
    cin >> x;
    cout << endl;

    //check if x is an integer
    if() //what are you going to do if the condition is true?
    {







    }
    else //just display x is not an integer
    {
        cout << x << " is not an integer." << endl;
    }

    cout << endl;
    return 0;
}
