// (c) name
// WK5 - PE

#include <iostream>
using namespace std;

int main( ) {

    enum workDay {sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday};
    int option;

    cout << "Days of the week:\n"
         << "0) Sunday\n"
         << "1) Monday\n"
         << "2) Tuesday\n"
         << "3) Wednesday\n"
         << "4) Thursday\n"
         << "5) Friday\n"
         << "6) Saturday\n"
         << "Select a day to take off: ";
    cin >> option; cout << endl;

    //use swithch() to to handle a menu above

















    cout << endl;
    return 0;
}
